/**
 * You are given two strings s and t.
 * <p>
 * String t is generated by random shuffling string s and then add one more letter at a random
 * position.
 * <p>
 * Return the letter that was added to t.
 */

public class FindTheDifference {

  public static void main(String[] args) {
    System.out.println(findTheDifference("abcd", "abcde"));
  }

  public static char findTheDifference(String s, String t) {
    char[] alphabet = new char[26];

    for (char c : t.toCharArray()) {
      alphabet[c - 'a'] += c;
    }

    for (char c : s.toCharArray()) {
      alphabet[c - 'a'] -= c;
    }

    for (char j : alphabet) {
      if (j > 0) {
        return j;
      }
    }
    return '\u0000';
  }

}
